parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    GuzzleHttp\Client:
        autowire: true

    guzzle.client.jira_api:
        class: 'GuzzleHttp\Client'
        arguments:
            - base_uri: '%env(JIRA_HOST)%'
              auth:
                  - '%env(JIRA_USER)%'
                  - '%env(JIRA_PASS)%'
              connect_timeout: 1
              exceptions: true

    guzzle.client.toggl_api:
        class: 'GuzzleHttp\Client'
        arguments:
            - base_uri: '%env(TOGGL_HOST)%'
              auth:
                  - '%env(TOGGL_API_KEY)%'
                  - 'api_token'
              connect_timeout: 1
              exceptions: true

    App\Api\JiraApi:
        arguments:
            - '@guzzle.client.jira_api'
            - '%env(DIFF_WITH_UTC_IN_HOURS)%'

    App\Api\TogglApi:
        arguments:
            - '@guzzle.client.toggl_api'

    App\Manager\TogglManager:
        public: true



