imports:
  - { resource: 'issue_key_map.yaml' }

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
          App\Service\TimeEntryStorage\TimeEntryStorage: '@App\Service\TimeEntryStorage\TimeEntryStorageSelector'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    GuzzleHttp\Client:
        autowire: true

    guzzle.client.jira_api:
        class: 'GuzzleHttp\Client'
        arguments:
            - base_uri: '%env(JIRA_HOST)%'
              auth:
                  - '%env(JIRA_USER)%'
                  - '%env(JIRA_PASS)%'
              connect_timeout: 3
              exceptions: true

    guzzle.client.toggl_api:
        class: 'GuzzleHttp\Client'
        arguments:
            - base_uri: '%env(TOGGL_HOST)%'
              auth:
                  - '%env(TOGGL_API_KEY)%'
                  - 'api_token'
              connect_timeout: 3
              exceptions: true

    guzzle.client.clockify_api:
      class: 'GuzzleHttp\Client'
      arguments:
        - base_uri: '%env(CLOCKIFY_HOST)%'
          headers:
            X-Api-Key: '%env(CLOCKIFY_API_KEY)%'
          connect_timeout: 3
          exceptions: true

    App\Api\JiraApi:
        arguments:
            - '@guzzle.client.jira_api'

    App\Api\TogglApi:
        arguments:
            - '@guzzle.client.toggl_api'

    App\Api\ClockifyApi:
      arguments:
        - '@guzzle.client.clockify_api'
        - '%env(CLOCKIFY_USER_ID)%'
        - '%env(CLOCKIFY_WORKSPACE_ID)%'

    App\Service\TimeEntryToWorklogConverter\DefaultTimeEntryToWorklogConverter:
        arguments:
          $defaultIssueNum: '%env(DEFAULT_ISSUE_KEY)%'

    App\Service\TimeEntryStorage\TimeEntryStorageSelector:
      arguments:
        $selectedStorage: '%env(TRACKER_TYPE)%'
